[package]
name = "reqwest_mock"
version = "0.1.0"
authors = ["Leo Schwarz <mail@leoschwarz.com>"]
license = "Apache-2.0"

[dependencies]
error-chain = "0.10.0"
reqwest = "0.6.1"
serde = "1.0.6"
serde_derive = "1.0.6"
serde_json = "1.0.2"
serde_urlencoded = "0.5.0"
